# Generated by Django 4.2.30 on 2026-08-21 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("leasing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LandlordPayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payout_id",
                    models.CharField(editable=False, max_length=40, unique=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("paid_at", models.DateTimeField()),
                ("reference", models.CharField(blank=True, max_length=100)),
                ("status", models.CharField(default="PAID", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="RentInstallment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("due_date", models.DateField()),
                ("amount_due", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPCOMING", "À venir"),
                            ("PARTIAL", "Partiellement payé"),
                            ("PAID", "Payé"),
                            ("LATE", "En retard"),
                            ("REGULARIZED", "Régularisé"),
                        ],
                        default="UPCOMING",
                        max_length=20,
                    ),
                ),
                (
                    "lease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="installments",
                        to="leasing.lease",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(editable=False, max_length=40, unique=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("received_at", models.DateTimeField()),
                ("reference", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                (
                    "installment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="payments.rentinstallment",
                    ),
                ),
                (
                    "lease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_receipts",
                        to="leasing.lease",
                    ),
                ),
            ],
        ),
    ]
