# Generated by Django 4.2.30

import users.models
from django.db import migrations, models
import core.validators


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_identityverification_facial_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityverification',
            name='facial_photo',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=users.models.facial_upload_path,
                validators=[core.validators.validate_image_upload],
            ),
        ),
    ]
