# Generated by Django 4.2.30 on 2026-08-21 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("properties", "0001_initial"),
        ("leasing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentalcase",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rental_cases",
                to="properties.property",
            ),
        ),
    ]
