# Generated by Django 4.2.30 on 2026-08-21 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("properties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("leasing", "0002_initial"),
        ("visits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentalcase",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rental_cases_as_tenant",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rentalcase",
            name="visit",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rental_case",
                to="visits.visitrequest",
            ),
        ),
        migrations.AddField(
            model_name="renewalrequest",
            name="decided_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="decided_renewals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="renewalrequest",
            name="lease",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="renewal_requests",
                to="leasing.lease",
            ),
        ),
        migrations.AddField(
            model_name="renewalrequest",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="renewal_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leaseexit",
            name="decided_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="decided_lease_exits",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leaseexit",
            name="lease",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="exit_requests",
                to="leasing.lease",
            ),
        ),
        migrations.AddField(
            model_name="leaseexit",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lease_exit_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="lease",
            name="landlord",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="leases_as_landlord",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="lease",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="leases",
                to="properties.property",
            ),
        ),
        migrations.AddField(
            model_name="lease",
            name="rental_case",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lease",
                to="leasing.rentalcase",
            ),
        ),
        migrations.AddField(
            model_name="lease",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="leases_as_tenant",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
