# Generated by Django 4.2.30 on 2026-08-21 11:26

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_id",
                    models.CharField(editable=False, max_length=40, unique=True),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("TENANT", "Sofasthome - Locataire"),
                            ("LANDLORD", "Sofasthome - Bailleur"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("SIGNED", "Signé"),
                            ("UPLOADED", "Téléversé"),
                            ("VALIDATED", "Validé"),
                            ("REJECTED", "Rejeté"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "signed_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="private/contracts/",
                        validators=[core.validators.validate_identity_document],
                    ),
                ),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
