from django.urls import path
from . import views
from . import property_views
from . import contract_views
from . import publication_views, verification_views, lease_lifecycle_views
from visits import views as visit_views

urlpatterns = [
    path('', views.activity, name='activity'),
    path('properties/', property_views.my_properties, name='my_properties'),
    path('properties/<str:property_id>/', property_views.property_manage, name='property_manage'),
    path('properties/<str:property_id>/review/', property_views.property_review, name='property_review'),
    path('properties/<str:property_id>/submit/', property_views.property_submit, name='property_submit'),
    path('properties/<str:property_id>/delete-draft/', property_views.property_delete_draft, name='property_delete_draft'),
    path('favorites/', views.favorites, name='favorites'),
    path('favorites/<str:property_id>/toggle/', views.toggle_favorite, name='toggle_favorite'),
    path('notifications/', views.notifications, name='notifications'),
    path('notifications/<str:notification_id>/read/', views.mark_notification_read, name='mark_notification_read'),
    path('notifications/read-all/', views.mark_all_notifications_read, name='mark_all_notifications_read'),
    path('notifications/unread-count/', views.notification_unread_count, name='notification_unread_count'),
    path('visits/', views.visits_page, name='visits'),
    path('visits/<str:visit_id>/landlord-decision/', visit_views.landlord_visit_decision, name='landlord_visit_decision'),
    path('visits/<str:visit_id>/fasthome-decision/', visit_views.fasthome_visit_decision, name='fasthome_visit_decision'),
    path('visits/<str:visit_id>/complete/', visit_views.mark_visit_completed, name='mark_visit_completed'),
    path('visits/<str:visit_id>/tenant-decision/', visit_views.tenant_decision, name='tenant_decision'),
    path('leases/<str:lease_id>/', views.lease_detail, name='lease_detail'),
    path('leases/<str:lease_id>/requests/', lease_lifecycle_views.lease_requests, name='lease_requests'),
    path('leases/<str:lease_id>/renew/', lease_lifecycle_views.request_renewal, name='request_renewal'),
    path('leases/<str:lease_id>/exit/', lease_lifecycle_views.request_exit, name='request_exit'),
    path('contracts/<str:contract_id>/document/', contract_views.contract_document, name='contract_document'),
    path('office/', views.office_dashboard, name='office_dashboard'),
    path('office/users/', views.office_users, name='office_users'),
    path('office/publications/', publication_views.office_publications, name='office_publications'),
    path('office/publications/<str:publication_id>/decision/', publication_views.office_publication_decision, name='office_publication_decision'),
    path('office/verifications/', verification_views.office_verifications, name='office_verifications'),
    path('office/verifications/<int:verification_id>/document/', verification_views.office_verification_document, name='office_verification_document'),
    path('office/verifications/<int:verification_id>/decision/', verification_views.office_verification_decision, name='office_verification_decision'),
    path('office/visits/', views.office_visits, name='office_visits'),
    path('office/visits/<str:visit_id>/approve/', views.office_approve_visit, name='office_approve_visit'),
    path('office/visits/<str:visit_id>/complete/', views.office_complete_visit, name='office_complete_visit'),
    path('office/cases/', views.office_cases, name='office_cases'),
    path('office/cases/<str:case_id>/accept/', views.office_accept_case, name='office_accept_case'),
    path('office/contracts/', views.office_contracts, name='office_contracts'),
    path('office/contracts/<str:contract_id>/upload/', views.office_contract_upload, name='office_contract_upload'),
    path('office/contracts/<str:contract_id>/validate/', views.office_contract_validate, name='office_contract_validate'),
    path('office/pv/', views.office_reports, name='office_reports'),
    path('office/pv/<str:report_id>/validate/', views.office_report_validate, name='office_report_validate'),
    path('office/leases/<str:lease_id>/officialize/', views.office_officialize_lease, name='office_officialize_lease'),
    path('office/lifecycle/', lease_lifecycle_views.office_lifecycle_requests, name='office_lifecycle_requests'),
    path('office/lifecycle/renewals/<str:request_id>/decision/', lease_lifecycle_views.decide_renewal, name='decide_renewal'),
    path('office/lifecycle/exits/<str:exit_id>/decision/', lease_lifecycle_views.decide_exit, name='decide_exit'),
    path('office/payments/receipt/', views.office_receipt, name='office_receipt'),
    path('office/payments/payout/', views.office_payout, name='office_payout'),
]
