# Generated by Django 4.2.30 on 2026-08-21 11:26

import core.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bathroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("INTERIOR", "Intérieure"),
                            ("EXTERIOR", "Extérieure"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "access_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PRIVATE", "Privée"),
                            ("PUBLIC", "Publique / commune"),
                        ],
                        max_length=10,
                    ),
                ),
                ("hot_water", models.BooleanField(default=False)),
                ("shower", models.BooleanField(default=False)),
                ("bathtub", models.BooleanField(default=False)),
                ("sink", models.BooleanField(default=False)),
                ("mirror", models.BooleanField(default=False)),
                ("storage", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Bedroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("bed_type", models.CharField(blank=True, max_length=50)),
                ("mattress", models.BooleanField(default=False)),
                ("wardrobe", models.BooleanField(default=False)),
                ("bedside_table", models.BooleanField(default=False)),
                ("desk", models.BooleanField(default=False)),
                ("chair", models.BooleanField(default=False)),
                ("curtains", models.BooleanField(default=False)),
                ("mosquito_net", models.BooleanField(default=False)),
                ("fan", models.BooleanField(default=False)),
                ("air_conditioning", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="CollaborationConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verification_accepted", models.BooleanField(default=False)),
                ("presentation_accepted", models.BooleanField(default=False)),
                ("visits_accepted", models.BooleanField(default=False)),
                ("management_accepted", models.BooleanField(default=False)),
                ("collaboration_accepted", models.BooleanField(default=False)),
                ("terms_version", models.CharField(max_length=50)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Kitchen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("equipped", models.BooleanField(default=False)),
                ("stove", models.BooleanField(default=False)),
                ("oven", models.BooleanField(default=False)),
                ("refrigerator", models.BooleanField(default=False)),
                ("freezer", models.BooleanField(default=False)),
                ("microwave", models.BooleanField(default=False)),
                ("hood", models.BooleanField(default=False)),
                ("sink", models.BooleanField(default=False)),
                ("cupboards", models.BooleanField(default=False)),
                ("table", models.BooleanField(default=False)),
                ("chairs", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="LivingRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("sofa", models.BooleanField(default=False)),
                ("coffee_table", models.BooleanField(default=False)),
                ("tv_cabinet", models.BooleanField(default=False)),
                ("television", models.BooleanField(default=False)),
                ("curtains", models.BooleanField(default=False)),
                ("fan", models.BooleanField(default=False)),
                ("air_conditioning", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "property_id",
                    models.CharField(editable=False, max_length=32, unique=True),
                ),
                ("furnished", models.BooleanField(default=False)),
                ("province", models.CharField(max_length=100)),
                ("city_or_territory", models.CharField(max_length=120)),
                (
                    "administrative_subdivision",
                    models.CharField(blank=True, max_length=160),
                ),
                ("neighborhood", models.CharField(blank=True, max_length=160)),
                ("exact_address", models.TextField(blank=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("google_maps_url", models.URLField(blank=True)),
                ("bedroom_count", models.PositiveIntegerField(default=0)),
                ("living_room_count", models.PositiveIntegerField(default=0)),
                ("has_kitchen", models.BooleanField(default=False)),
                ("bathroom_count", models.PositiveIntegerField(default=0)),
                ("toilet_count", models.PositiveIntegerField(default=0)),
                ("floor", models.CharField(blank=True, max_length=80)),
                ("ceiling_type", models.CharField(blank=True, max_length=100)),
                ("floor_type", models.CharField(blank=True, max_length=100)),
                (
                    "monthly_rent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "guarantee_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("max_occupants", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Brouillon"),
                            ("UNDER_REVIEW", "En vérification"),
                            ("AVAILABLE", "Disponible"),
                            ("RENTED", "Loué"),
                            ("SUSPENDED", "Suspendu"),
                            ("CLOSED", "Clôturé"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("furniture_condition", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PropertyType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Toilet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("INTERIOR", "Intérieure"),
                            ("EXTERIOR", "Extérieure"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "access_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PRIVATE", "Privée"),
                            ("PUBLIC", "Publique / commune"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "toilet_type",
                    models.CharField(
                        choices=[
                            ("BOWL", "Cuve"),
                            ("TURKISH", "Turque"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="toilets",
                        to="properties.property",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PropertyPublication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "publication_id",
                    models.CharField(editable=False, max_length=32, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Brouillon"),
                            ("SUBMITTED", "Soumis"),
                            ("UNDER_REVIEW", "En vérification"),
                            ("CORRECTION_REQUIRED", "À corriger"),
                            ("PUBLISHED", "Publié"),
                            ("SUSPENDED", "Suspendu"),
                            ("RENTED", "Loué"),
                        ],
                        default="DRAFT",
                        max_length=25,
                    ),
                ),
                ("correction_message", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "property",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publication",
                        to="properties.property",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PropertyPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="properties/photos/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png", "webp"]
                            ),
                            core.validators.validate_image_upload,
                        ],
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("GENERAL", "Générale"),
                            ("EXTERIOR", "Extérieur"),
                            ("LIVING_ROOM", "Salon"),
                            ("BEDROOM", "Chambre"),
                            ("KITCHEN", "Cuisine"),
                            ("BATHROOM", "Salle de bain"),
                            ("TOILET", "Toilette"),
                            ("PARKING", "Parking"),
                            ("GARDEN", "Jardin"),
                            ("OTHER", "Autre"),
                        ],
                        default="GENERAL",
                        max_length=20,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="properties.property",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PropertyFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=80)),
                ("value", models.CharField(blank=True, max_length=255)),
                ("category", models.CharField(blank=True, max_length=60)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="properties.property",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PropertyDeclaration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("relationship_to_property", models.CharField(max_length=80)),
                ("right_to_offer_confirmed", models.BooleanField(default=False)),
                ("accuracy_confirmed", models.BooleanField(default=False)),
                ("photos_authentic_confirmed", models.BooleanField(default=False)),
                ("authorization_confirmed", models.BooleanField(default=False)),
                ("acknowledged_responsibility", models.BooleanField(default=False)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "publication",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="declaration",
                        to="properties.propertypublication",
                    ),
                ),
            ],
        ),
    ]
