# Generated by Django 4.2.30 on 2026-08-21 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("properties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="properties",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="property_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="properties.propertytype",
            ),
        ),
        migrations.AddField(
            model_name="livingroom",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="living_rooms",
                to="properties.property",
            ),
        ),
        migrations.AddField(
            model_name="kitchen",
            name="property",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kitchen",
                to="properties.property",
            ),
        ),
        migrations.AddField(
            model_name="favorite",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorited_by",
                to="properties.property",
            ),
        ),
        migrations.AddField(
            model_name="favorite",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorites",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="collaborationconsent",
            name="publication",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collaboration_consent",
                to="properties.propertypublication",
            ),
        ),
        migrations.AddField(
            model_name="bedroom",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bedrooms",
                to="properties.property",
            ),
        ),
        migrations.AddField(
            model_name="bathroom",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bathrooms",
                to="properties.property",
            ),
        ),
        migrations.AddConstraint(
            model_name="favorite",
            constraint=models.UniqueConstraint(
                fields=("user", "property"), name="unique_favorite"
            ),
        ),
    ]
