# Generated by Django 4.2.30 on 2026-08-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MatchingResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("criteria_breakdown", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-score"],
            },
        ),
        migrations.CreateModel(
            name="SearchRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "furnished_preference",
                    models.CharField(
                        choices=[("YES", "Oui"), ("NO", "Non"), ("ANY", "Peu importe")],
                        default="ANY",
                        max_length=3,
                    ),
                ),
                ("province", models.CharField(max_length=100)),
                ("city_or_territory", models.CharField(max_length=120)),
                (
                    "administrative_subdivision",
                    models.CharField(blank=True, max_length=160),
                ),
                ("neighborhood", models.CharField(blank=True, max_length=160)),
                ("minimum_living_rooms", models.PositiveIntegerField(default=0)),
                ("minimum_bedrooms", models.PositiveIntegerField(default=0)),
                (
                    "maximum_budget",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("requested_occupants", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
