# Generated by Django 4.2.30 on 2026-08-21 11:26

import uuid
from django.db import migrations, models
from django.conf import settings
import django.db.models.deletion


def generate_notification_id():
    return f"NTF-{uuid.uuid4().hex[:10].upper()}"


class Migration(migrations.Migration):
    initial = True
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_id",
                    models.CharField(
                        default=generate_notification_id,
                        editable=False,
                        max_length=40,
                        unique=True,
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("ACTION", "Action requise"),
                            ("INFO", "Information"),
                            ("SUCCESS", "Réussite"),
                        ],
                        default="INFO",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("object_type", models.CharField(blank=True, max_length=80)),
                ("object_id", models.CharField(blank=True, max_length=80)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
